name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
      
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board: ['arduino:avr:uno', 'Seeeduino:samd:seeed_XIAO_m0']

    steps:
      - uses: actions/checkout@v2
      - uses: arduino/actions/libraries/compile-examples@master
        with:
          fqbn: ${{ matrix.board }}
