name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
      
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board:
          - 'arduino:avr:uno'
          - '"Seeeduino:samd:seeed_XIAO_m0" "http://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json"'

    steps:
      - uses: actions/checkout@v2
      - uses: arduino/actions/libraries/compile-examples@master
        with:
          fqbn: ${{ matrix.board }}
          libraries: |
            - source_url: https://github.com/Seeed-Studio/Seeed_Arduino_atWiFi.git
            - source_url: https://github.com/Seeed-Studio/Seeed_Arduino_FreeRTOS.git
            - source_url: https://github.com/Seeed-Studio/esp-at-lib.git
            - source_url: https://github.com/Seeed-Studio/Seeed_Arduino_atUnified.git
            - source_url: https://github.com/Seeed-Studio/Seeed_Arduino_mbedtls.git
            - source_url: https://github.com/Seeed-Studio/Seeed_Arduino_atWiFiClientSecure.git
            - source_url: https://github.com/Seeed-Studio/Seeed_Arduino_atHTTPClient.git
